services:
  exporter:
    image: registry.gitlab.com/oroessner/anker-solix-prom-exporter
    build: .
    ports:
      - "127.0.0.1:9123:9123"
    env_file:
      - .env
    volumes:
      - ./src/anker_solix_prom_exporter:/anker_solix_prom_exporter:ro
  
  prometheus:
    image: prom/prometheus:v3.5.0
    ports:
      - "127.0.0.1:9090:9090"
    depends_on:
      - exporter
    volumes:
      - ./.docker/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=60d'
