global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: solix
    static_configs:
      - targets:
          - exporter:9123

    relabel_configs:
      - source_labels: [__address__]
        regex: "([^:]+):\\d+"
        target_label: instance
